### PR TITLE
Tweak enough to generate first-pass CQL

### PR DESCRIPTION
**Pull request by cjheath**
Hi, I made a VS project to tweak your ORM files to fix most of the errors that prevent them from loading in ActiveFacts, to generate into CQL - which is included here.

### CODE REVIEW

**Comment by cjheath** [comment]
Do you care to fix the remaining NORMA errors? I would then tweak further to make the generated CQL compile...

**Comment by tynman** [comment]
Yeah, I'll try to get those resolved tomorrow night. Made the mistake of installing VS2015 Update 1, and it's still running. Thanks for the contribution!

**Comment by tynman** [comment]
Really dumb question... do you know for certain that there -are- NORMA
errors? I opened them in VS and haven't run into any problems.

**Comment by cjheath** [comment]
Yes, there are many errors, especially missing identifiers and errors in sample
populations. You need to open each model, not just the solution, before the
validation is performed. Then look in the error window. Sorry I seem to have
caused a number of file errors by trying to put the NORMA-generated files in
a different directory from the bare ORM files.

Clifford Heath.

**Comment by tynman** [comment]
Done! Should be, at least. I reformatted my machine and haven't installed
NORMA Pro, so there's one subset constraint in the WebTickets.orm model
that I deleted since I couldn't define the join path. There's a note now in
its stead.

**Pull request merged**
